- name: Create haproxy service dir
  ansible.builtin.file:
    path: "/services/haproxy"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy haproxy config file
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "/services/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: "0644"

- name: Copy docker-compose file
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/services/haproxy/docker-compose.yml"
    owner: root
    group: root
    mode: "0640"

- name: Launch haproxy
  community.docker.docker_compose_v2:
    state: present
    project_src: "/services/haproxy"
    files:
      - "docker-compose.yml"
