{{- if gt (int .Values.rustfs.replicaCount) 1 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rustfs
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
