gatewayIp: "{{ hostvars[groups['gateway'][0]]['ansible_host'] }}"
haproxy:
  version: "alpine3.22"
  extraKubeAllowedIps: ""
  allowedIps: "192.168.27.64/27"
  statsPassword: "{{ vault_haproxy_stats_password | default('') }}"
pihole:
  enabled: true
  version: "2026.04.1"
  domain: pihole.{{ localRootDomain }}
  password: "{{ vault_pihole_password }}"
wireguard:
  enabled: false
  version: "15"
  domain: "vpn.{{ rootDomain }}"
  password: "{{ vault_wireguard_password }}"
  ipRange: "192.168.27.x"
  # allowedIps: ""
