apiVersion: v2
name: homepage
type: application
version: 1.8.4
appVersion: "1.13.1"
dependencies:
- name: homepage
  alias: homepage
  version: 1.8.4
  repository: https://unknowniq.github.io/helm-charts/
