---
- name: Ensure k3s config directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Deploy k3s token file
  ansible.builtin.copy:
    content: "{{ k3sToken }}"
    dest: /etc/rancher/k3s/token
    owner: root
    group: root
    mode: "0600"
  no_log: true

- name: Copy k3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "{{ k3sSystemdDir }}/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable and check k3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true
  timeout: 360
