apiVersion: v2
name: rustfs
type: application
version: 0.1.0
dependencies:
- name: rustfs
  alias: rustfs
  version: 1.0.1
  repository: https://charts.rustfs.com
- name: vso-utils
  alias: vso
  version: 2.1.0
  repository: https://this-is-tobi.github.io/helm-charts
