apiVersion: v2
name: cloudnative-pg
type: application
version: 0.28.3
appVersion: "1.29.1"
dependencies:
- name: cloudnative-pg
  alias: cloudnative-pg
  version: 0.28.3
  repository: https://cloudnative-pg.github.io/charts
- name: plugin-barman-cloud
  alias: plugin-barman-cloud
  version: 0.7.0
  repository: https://cloudnative-pg.github.io/charts
