---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sops-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sops
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sops
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
