---
galaxy_info:
  author: this-is-tobi
  role_name: storage
  namespace: k3s
  license: MIT
  description: Install iSCSI/NFS packages and mount additional storage disks.
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bookworm]
  galaxy_tags: [k3s, kubernetes, storage, longhorn]
dependencies: []
