apiVersion: v2
name: argo-workflows
type: application
version: 0.1.0
dependencies:
- name: argo-workflows
  alias: argo-workflows
  version: 2.0.8
  repository: https://argoproj.github.io/argo-helm
- name: vso-utils
  alias: vso
  version: 2.1.0
  repository: https://this-is-tobi.github.io/helm-charts
