# Ansible infos
ansible_user: devops
ansible_port: 22
ansible_password: "{{ vault_ansible_password }}"
# Lab domains
rootDomain: "example.domain.com"
localRootDomain: "example.domain.local"
# Admin users
adminUsers: []
# - username: ""
#   sshPubKey: ""
#   state: present # absent
