- name: Update all packages on a Debian/Ubuntu
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_upgrade_reboot_required

- name: Reboot if required by the system
  ansible.builtin.reboot:
    msg: "Rebooting to apply system updates"
    reboot_timeout: 300
  when: common_upgrade_reboot_required.stat.exists

- name: Verify new kernel version
  ansible.builtin.command: uname -mrs
  register: common_uname_result
  changed_when: false

- name: Display new kernel version
  ansible.builtin.debug:
    var: common_uname_result.stdout_lines
