---
galaxy_info:
  author: this-is-tobi
  role_name: registry
  namespace: k3s
  license: MIT
  description: Configure private container registry (Harbor) on K3s nodes.
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bookworm]
  galaxy_tags: [k3s, kubernetes, registry, harbor]
dependencies: []
