- name: Remove wireguard when disabled
  when: not wireguard.enabled
  block:
    - name: Stop wireguard if running
      community.docker.docker_compose_v2:
        state: absent
        project_src: "/services/wireguard"
        files:
          - "docker-compose.yml"
      ignore_errors: true

    - name: Remove wireguard service dir
      ansible.builtin.file:
        path: "/services/wireguard"
        state: absent

- name: Deploy wireguard when enabled
  when: wireguard.enabled
  block:
    - name: Set wireguard password
      ansible.builtin.set_fact:
        gateway_wireguard_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=24, chars=['ascii_letters', 'digits']) }}"

    - name: Fetch wireguard password
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        content: "{{ gateway_wireguard_password }}"
        dest: "{{ playbook_dir }}/inventory/group_vars/.wireguard_password"
        mode: "0600"
      when: wireguard.password == ''

    - name: Create wireguard service dir
      ansible.builtin.file:
        path: "/services/wireguard"
        state: directory
        owner: root
        group: root
        mode: "0750"

    - name: Copy wireguard env file
      ansible.builtin.template:
        src: "wireguard.env.j2"
        dest: "/services/wireguard/.env.wireguard"
        owner: root
        group: root
        mode: "0600"
      no_log: true

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "/services/wireguard/docker-compose.yml"
        owner: root
        group: root
        mode: "0640"

    - name: Launch wireguard
      community.docker.docker_compose_v2:
        state: present
        project_src: "/services/wireguard"
        files:
          - "docker-compose.yml"

    - name: Create wireguard users
      ansible.builtin.include_tasks: users.yml
      loop: "{{ adminUsers }}"
