#!/usr/bin/env bash
# Unit-tests the CEL policies and exceptions the kyverno chart renders. The
# chart is rendered the way production does (homelab instance values first,
# the documented _example as fallback), the policies.kyverno.io objects are
# exported, and `kyverno test` runs every <chart>/tests/policies/<name>/.
# Fixture files reference ../../rendered/policies.yaml and
# ../../rendered/exceptions.yaml.
#
# The CLI cannot evaluate namespaceObject and reports a resource a policy does
# not apply to as a passing result whatever the test expects. So the tenant
# scoping variable (outOfScope, which reads the namespace labels) is overridden
# to false in the exported policies, and a fixture with no evaluated row for its
# policy fails the run. The scoping itself is checked on a real cluster.
#
# Every ValidatingPolicy must also share one Kyverno webhook: a namespaceSelector,
# matchConditions or webhookConfiguration of its own gives it a webhook of its
# own, which costs one more admission call per pod and policy. Scope inside the
# expressions instead (see kyverno.cel.scope).
set -euo pipefail

chart="${1:-argo-cd/apps/kyverno}"
name=$(basename "$chart")
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
failures=0

shopt -s nullglob
dirs=("$chart"/tests/policies/*/)
if [ "${#dirs[@]}" -eq 0 ]; then
  echo "no policy fixtures under $chart/tests/policies"
  exit 0
fi
command -v kyverno >/dev/null || { echo "kyverno CLI not found on PATH (v1.19.1 expected)" >&2; exit 2; }

values_args() {
  local inst scope vf
  for inst in homelab _example; do
    for scope in core tenant; do
      vf="argo-cd/instances/$inst/values/$scope/$name.yaml"
      if [ -f "$vf" ]; then printf '%s\n' -f "$vf"; return; fi
    done
  done
}
mapfile -t args < <(values_args)

mkdir -p "$work/rendered" "$work/tests"
helm template ci "$chart" --namespace kyverno "${args[@]}" >"$work/all.yaml"
yq ea 'select((.apiVersion // "") | test("^policies\\.kyverno\\.io/")) | select(.kind != "PolicyException") | (.spec.variables[]? | select(.name == "outOfScope" and (.expression | contains("namespaceObject"))) | .expression) = "false"' "$work/all.yaml" >"$work/rendered/policies.yaml"
yq ea 'select((.apiVersion // "") | test("^policies\\.kyverno\\.io/")) | select(.kind == "PolicyException")' "$work/all.yaml" >"$work/rendered/exceptions.yaml"

own_webhook=$(yq ea 'select(.kind == "ValidatingPolicy") | select(.spec.matchConstraints.namespaceSelector or .spec.matchConstraints.objectSelector or .spec.matchConditions or .spec.webhookConfiguration) | .metadata.name' "$work/all.yaml")
if [ -n "$own_webhook" ]; then
  echo "::error::these ValidatingPolicies would get a Kyverno webhook of their own (namespaceSelector, objectSelector, matchConditions or webhookConfiguration): $own_webhook"
  failures=$((failures + 1))
fi

for d in "${dirs[@]}"; do
  t=$(basename "$d")
  cp -R "$d" "$work/tests/$t"
  echo "::group::$t"
  rc=0
  (cd "$work/tests/$t" && kyverno test . --remove-color) >"$work/$t.out" 2>&1 || rc=1
  cat "$work/$t.out"
  # A workload kind has two rows per policy (the pod rule, which excludes it, and
  # the autogenerated one), so only a policy/resource pair with no evaluated row counts.
  if ! unevaluated=$(awk -F'│' '
      /^│ *[0-9]+ / {
        for (i = 3; i <= 7; i++) gsub(/^ +| +$/, "", $i)
        k = $3 " " $5; seen[k] = 1
        if ($7 != "Excluded") evaluated[k] = 1
      }
      END { for (k in seen) if (!(k in evaluated)) { print k; bad = 1 } exit bad }' "$work/$t.out"); then
    echo "::error::$t: fixtures never evaluated by their policy (the CLI reports that as a pass whatever is expected):"
    echo "$unevaluated"
    rc=1
  fi
  [ "$rc" -eq 0 ] || failures=$((failures + 1))
  echo "::endgroup::"
done

exit "$failures"
