apiVersion: v2
name: mattermost
type: application
version: 6.6.94
appVersion: "11.5.1"
dependencies:
- name: mattermost-team-edition
  alias: mattermost
  version: 6.6.94
  repository: https://helm.mattermost.com
- name: cnpg-cluster
  alias: cnpg
  version: 1.7.1
  repository: https://this-is-tobi.github.io/helm-charts
- name: vso-utils
  alias: vso
  version: 1.1.7
  repository: https://this-is-tobi.github.io/helm-charts
