apiVersion: v2
name: sonarqube
type: application
version: 0.1.0
appVersion: "26.3.0.120487"
dependencies:
- name: sonarqube
  alias: sonarqube
  version: 2026.2.1
  repository: https://SonarSource.github.io/helm-chart-sonarqube
- name: cluster
  alias: cnpg
  version: 0.9.0
  repository: https://cloudnative-pg.github.io/charts
- name: vso-utils
  alias: vso
  version: 2.1.0
  repository: https://this-is-tobi.github.io/helm-charts
