apiVersion: v2
name: outline
type: application
version: 0.1.0
dependencies:
- name: outline
  alias: outline
  version: 0.9.5
  repository: https://community-charts.github.io/helm-charts
- name: valkey
  alias: valkey
  version: 0.25.13
  repository: oci://registry-1.docker.io/cloudpirates
- name: cluster
  alias: cnpg
  version: 0.9.0
  repository: https://cloudnative-pg.github.io/charts
- name: vso-utils
  alias: vso
  version: 2.1.0
  repository: https://this-is-tobi.github.io/helm-charts
