---
galaxy_info:
  author: this-is-tobi
  role_name: users
  namespace: k3s
  license: MIT
  description: Create Kubernetes users with x509 certificates and RBAC.
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: [bookworm]
  galaxy_tags: [k3s, kubernetes, users, rbac]
dependencies: []
