{
 "title": "Harbor",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "harbor health",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "harbor_health" }
     ]
    },
    {
     "title": "component up status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_up" }
     ]
    },
    {
     "title": "system info",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_system_info" }
     ]
    },
    {
     "title": "artifact pulled",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_artifact_pulled" }
     ]
    },
    {
     "title": "Project total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_project_total" }
     ]
    },
    {
     "title": "project members",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_project_member_total" }
     ]
    },
    {
     "title": "Quota Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_project_quota_usage_byte"
      }
     ]
    },
    {
     "title": "Project repo total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_project_repo_total" }
     ]
    }
   ]
  },
  {
   "title": "Genertal metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "go info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_info" }
     ]
    },
    {
     "title": "Process CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_cpu_seconds_total" }
     ]
    },
    {
     "title": "go threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_threads" }
     ]
    },
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_goroutines" }
     ]
    },
    {
     "title": "Process opened fd",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_open_fds" }
     ]
    },
    {
     "title": "Go heap objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_heap_objects" }
     ]
    },
    {
     "title": "go allocated  memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_alloc_bytes" }
     ]
    },
    {
     "title": "go next gc bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_next_gc_bytes" }
     ]
    },
    {
     "title": "go gc time 0.25",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.25\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.5\"}"
      }
     ]
    },
    {
     "title": "go gc time 0.75",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.75\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "API request time 0.5",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.5\"}"
      }
     ]
    },
    {
     "title": "request time 0.9",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.9\"}",
       "legendFormat": "{{instance}}-{{operation}}"
      }
     ]
    },
    {
     "title": "request time 0.99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "harbor core request total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(harbor_core_http_request_total[5m])"
      }
     ]
    },
    {
     "title": "harbor core inflight request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_core_http_inflight_requests"
      }
     ]
    }
   ]
  },
  {
   "title": "JobService Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "job service info",
     "type": "graph",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_jobservice_info" }
     ]
    },
    {
     "title": "task queue pending size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_size" }
     ]
    },
    {
     "title": "task latency",
     "type": "graph",
     "description": "time period from last process of task queue",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_queue_latency" }
     ]
    },
    {
     "title": "task concurrency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_concurrency" }
     ]
    },
    {
     "title": "tasks per minute",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(harbor_jobservice_task_total[1m])"
      }
     ]
    },
    {
     "title": "number of running scheduled job",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "harbor_task_scheduled_total" }
     ]
    },
    {
     "title": "task process time 0.5",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.5\"}"
      }
     ]
    },
    {
     "title": "task process time 0.9",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.9\"}"
      }
     ]
    },
    {
     "title": "task process time 0.99",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "harbor_jobservice_task_process_time_seconds{quantile=\"0.99\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registry request inflight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "registry_http_in_flight_requests"
      }
     ]
    },
    {
     "title": "Registry request rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_http_requests_total[5m])"
      }
     ]
    },
    {
     "title": "registry storage cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(registry_storage_cache_total[5m])"
      }
     ]
    },
    {
     "title": "registry request time 0.5",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(registry_http_request_duration_seconds_bucket[10m]))"
      }
     ]
    },
    {
     "title": "registry request time 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket[10m]))"
      }
     ]
    },
    {
     "title": "registry request time 0.99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(registry_http_request_duration_seconds_bucket[10m]))"
      }
     ]
    },
    {
     "title": "registry request size 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_request_size_bytes_bucket[10m]))"
      }
     ]
    },
    {
     "title": "registry response size 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_http_response_size_bytes_bucket[10m]))"
      }
     ]
    },
    {
     "title": "registry storage action time 0.9",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, rate(registry_storage_action_seconds_bucket[10m]))"
      }
     ]
    }
   ]
  }
 ]
}