apiVersion: v2
name: crowdsec
type: application
version: 0.1.0
dependencies:
  - name: crowdsec
    alias: crowdsec
    version: 0.24.2
    repository: https://crowdsecurity.github.io/helm-charts
  - name: cluster
    alias: cnpg
    version: 0.9.0
    repository: https://cloudnative-pg.github.io/charts
  - name: vso-utils
    alias: vso
    version: 2.1.0
    repository: https://this-is-tobi.github.io/helm-charts
