apiVersion: v2
name: gitea
type: application
version: 0.1.0
dependencies:
- name: gitea
  alias: gitea
  version: 12.7.0
  repository: https://dl.gitea.com/charts
- name: valkey
  alias: valkey
  version: 0.25.13
  repository: oci://ghcr.io/cloudpirates-io/helm-charts
- name: cluster
  alias: cnpg
  version: 0.9.0
  repository: https://cloudnative-pg.github.io/charts
- name: vso-utils
  alias: vso
  version: 2.1.0
  repository: https://this-is-tobi.github.io/helm-charts

